version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Print the Current Time
          command: date
